import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowRight, ChevronRight } from "lucide-react";
import { docsOrder, platformModuleBySlug, platformModules } from "@/app/platform/platform-content";
import { notFound } from "next/navigation";

const details: Record<string, { intro: string; workflow: string[]; related: string[] }> = {
  admin: { intro: "The School Admin workspace is where a school establishes its operating model. It brings the records, settings, people, approvals, and daily controls together so teachers and parents can work from the same foundation.", workflow: ["Set up the school profile, academic years, terms, phases, classes, subjects, branding, payment information, and communication settings.", "Create staff, students, guardians, and the class and subject assignments that shape access.", "Run admissions, fees, attendance, assessments, timetable, announcements, support, and subscription workflows from one administrative view.", "Review analytics and reports, approve results, publish information, and prepare the next academic cycle."], related: ["teachers", "parents", "admissions", "academics", "fees"] },
  accounting: { intro: "Accounting gives the school’s finance team a dedicated workspace for wider financial operations. It is designed for clear recording, review, cashbook visibility, and practical reporting.", workflow: ["Create the income and expense categories the school uses.", "Record income and expenses, keeping expenses in draft where review is required.", "Approve and post expenses according to the school’s process.", "Review cashbook activity, compare income and expenses, reverse posted transactions with a reason when needed, and retain audit records."], related: ["fees", "admin", "reports"] },
  teachers: { intro: "The Teachers App gives each teacher a focused place to work with assigned classes and subjects. It keeps classroom activity close to the students and assessments the teacher is responsible for.", workflow: ["Open the dashboard, My Class, Students, Subjects, and Timetable areas for the current teaching context.", "Mark attendance and record available comments, observations, or daily reports.", "Open an assessment and enter scores for assigned subjects using the configured components.", "Review results and analytics while the School Admin manages formal approval and publication."], related: ["admin", "academics", "reports", "parents"] },
  parents: { intro: "The Parents App gives guardians a clear view of the children connected to their account. It brings together school information, attendance, published academic results, invoices, payments, and publications.", workflow: ["Sign in and select a linked child.", "Review attendance, published results, report cards, invoices, balances, and payment history.", "Use the available manual payment confirmation and school payment instructions when applicable.", "Read publications and school information in the same place as the child’s academic and fee context."], related: ["admin", "academics", "fees", "reports", "communication"] },
  admissions: { intro: "Admissions begins the relationship between a school and a new family. A school-specific admissions page collects the information staff need to review an application and continue the record inside SchoolBase.", workflow: ["The applicant opens the school’s admissions page while admissions are enabled and within the configured dates.", "They select a class and submit applicant, student, guardian, medical, previous-school, and photo information.", "The application receives a status that can be looked up using the available status flow.", "School staff review the application, update its status, and convert approved applications into student and guardian records where supported."], related: ["admin", "parents", "academics", "fees", "communication"] },
  academics: { intro: "Academics & Results follows the school’s academic cycle from structure to publication. It gives administrators control of the process while giving teachers the tools to enter the work they own.", workflow: ["Create the academic year, terms, phases, classes, subjects, and teacher assignments.", "Create assessments and configure their components.", "Teachers enter scores for assigned classes and subjects; SchoolBase validates and calculates grades, totals, and positions.", "Staff review the results, then the administrator controls approval, locking, publication, reports, and parent visibility."], related: ["admin", "teachers", "parents", "reports"] },
  fees: { intro: "Fees & Payments gives schools a flexible way to define what students owe and a clear way to explain it. Separate fee lines make charges such as tuition, books, sports, transport, or other school-defined items understandable to families.", workflow: ["Create a fee schedule for the relevant term, academic year, class, or student context.", "Add separate fee items and apply student-specific adjustments where needed.", "Generate and issue invoices, including bulk issuance, then track balances and reminders.", "Record payments, allocate them to invoice items, provide receipts or PDFs, and connect the payment to accounting activity where supported."], related: ["admin", "parents", "accounting", "reports", "communication"] },
  communication: { intro: "Communication connects important school events to the people who need to know. SchoolBase supports announcements plus email and WhatsApp messages around admissions, fees, attendance, results, and other school activity.", workflow: ["Configure school communication rules and available WhatsApp operations.", "An event such as an admission, invoice, payment, attendance mark, result publication, or announcement occurs.", "SchoolBase resolves the relevant audience and sends the available email or WhatsApp message.", "Delivery records and status controls are available where the channel supports them."], related: ["admin", "admissions", "fees", "academics", "parents"] },
  reports: { intro: "Reports & Analytics turns school records into useful visibility. Leadership can inspect performance, teachers can review academic context, and parents can receive the published reports that belong to their children.", workflow: ["Collect academic, attendance, fee, and accounting activity through normal school workflows.", "Use overview, class, subject, assessment, and performance analytics to see what needs attention.", "Generate broadsheets, rankings, statistics, report cards, transcripts, and bulk PDFs.", "Share the appropriate published report with teachers, parents, or public PIN-based result access."], related: ["academics", "teachers", "parents", "fees", "accounting"] },
};

export async function generateStaticParams() { return docsOrder.map((slug) => ({ slug })); }

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params; const platformModule = platformModuleBySlug[slug];
  if (!platformModule) return { title: "Documentation | SchoolBase", robots: { index: false, follow: false } };
  const url = `https://schoolbase.live/docs/${slug}`;
  return { title: `${platformModule.title} | SchoolBase Platform`, description: platformModule.summary, alternates: { canonical: url }, openGraph: { title: `${platformModule.title} | SchoolBase Platform`, description: platformModule.summary, url, type: "website" } };
}

export default async function DocumentationPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const platformModule = platformModuleBySlug[slug]; const content = details[slug];
  if (!platformModule || !content) notFound();
  const currentIndex = docsOrder.indexOf(slug); const previous = currentIndex > 0 ? platformModuleBySlug[docsOrder[currentIndex - 1]] : null; const next = currentIndex < docsOrder.length - 1 ? platformModuleBySlug[docsOrder[currentIndex + 1]] : null;
  return <div className="bg-background">
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{
        __html: JSON.stringify({
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          itemListElement: [
            { "@type": "ListItem", position: 1, name: "Platform", item: "https://schoolbase.live/platform" },
            { "@type": "ListItem", position: 2, name: platformModule.title, item: `https://schoolbase.live/docs/${slug}` },
          ],
        }),
      }}
    />
    <section className="border-b border-border bg-[#f6faff] py-14 sm:py-20"><div className="mx-auto max-w-6xl px-6"><div className="flex items-center gap-2 text-sm text-muted"><Link href="/platform" className="hover:text-brand">Platform</Link><ChevronRight className="h-4 w-4" /><span>{platformModule.title}</span></div><div className="mt-10 max-w-4xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-brand">{platformModule.eyebrow}</p><h1 className="mt-4 text-4xl font-bold tracking-tight text-foreground sm:text-6xl">{platformModule.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted sm:text-xl">{content.intro}</p></div></div></section>
    <main className="mx-auto grid max-w-6xl gap-12 px-6 py-14 lg:grid-cols-[minmax(0,1fr)_280px] lg:py-20"><article><section><h2 className="text-3xl font-bold tracking-tight text-foreground">What this area does</h2><p className="mt-5 max-w-3xl text-lg leading-8 text-muted">{platformModule.connects}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{platformModule.capabilities.map((capability) => <div key={capability} className="flex gap-3 border border-border bg-white p-4 text-sm leading-6 text-foreground"><span className="mt-0.5 text-brand">✓</span>{capability}</div>)}</div></section><section className="mt-16 border-t border-border pt-12"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-brand">The workflow</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-foreground">How {platformModule.title.toLowerCase()} works</h2><div className="mt-8 space-y-4">{content.workflow.map((step, index) => <div key={step} className="flex gap-5 border-l-2 border-brand/25 pl-5"><span className="text-sm font-bold text-brand">{String(index + 1).padStart(2, "0")}</span><p className="max-w-2xl leading-7 text-muted">{step}</p></div>)}</div></section><section className="mt-16 border-t border-border pt-12"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-brand">Related areas</p><h2 className="mt-4 text-3xl font-bold tracking-tight text-foreground">See the wider school system</h2><div className="mt-7 flex flex-wrap gap-3">{content.related.map((relatedSlug) => { const related = platformModuleBySlug[relatedSlug]; return <Link key={relatedSlug} href={`/docs/${relatedSlug}`} className="inline-flex items-center gap-2 border border-border bg-white px-4 py-3 text-sm font-semibold text-foreground hover:border-brand hover:text-brand">{related.title}<ArrowRight className="h-4 w-4" /></Link>; })}</div></section></article><aside className="lg:pt-1"><div className="border border-border bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand">Platform guide</p><p className="mt-3 text-sm leading-6 text-muted">Explore every SchoolBase area and see how the pieces connect.</p><Link href="/platform" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-brand">Back to platform <ArrowRight className="h-4 w-4" /></Link></div><div className="mt-4 border border-border bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-muted">In this guide</p><nav className="mt-4 space-y-2">{platformModules.map((item) => <Link key={item.slug} href={`/docs/${item.slug}`} className={`block border-l-2 py-1 pl-3 text-sm ${item.slug === slug ? "border-brand font-semibold text-brand" : "border-transparent text-muted hover:border-brand hover:text-brand"}`}>{item.title}</Link>)}</nav></div></aside></main>
    <section className="border-t border-border bg-white"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-6 px-6 py-10 sm:flex-row sm:items-center">{previous ? <Link href={`/docs/${previous.slug}`} className="group inline-flex items-center gap-3 text-sm font-semibold text-muted hover:text-brand"><ArrowLeft className="h-4 w-4 transition group-hover:-translate-x-1" /><span><span className="block text-xs font-normal text-muted">Previous</span>{previous.title}</span></Link> : <span />}{next ? <Link href={`/docs/${next.slug}`} className="group inline-flex items-center gap-3 text-right text-sm font-semibold text-muted hover:text-brand"><span><span className="block text-xs font-normal text-muted">Next</span>{next.title}</span><ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></Link> : <span />}</div></section>
    <section className="bg-brand py-14 text-white"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 px-6 sm:flex-row sm:items-center"><div><h2 className="text-2xl font-bold sm:text-3xl">Ready to see SchoolBase in your school?</h2><p className="mt-2 text-white/75">Start with the platform built for everyday school operations.</p></div><Link href="/signup" className="inline-flex items-center gap-2 rounded-lg bg-white px-5 py-3 text-sm font-semibold text-brand hover:bg-blue-50">Get Started <ArrowRight className="h-4 w-4" /></Link></div></section>
  </div>;
}
