import { MetadataRoute } from 'next'

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/purchase',
          '/demo',
          '/features',
          '/about',
          '/contact',
          '/privacy',
          '/terms',
          '/faq',
          '/solutions',
          '/solutions/school-owners',
          '/solutions/teachers',
          '/solutions/parents',
          '/solutions/administrators',
          '/solutions/school-fee-management',
          '/solutions/digital-result-management',
          '/solutions/student-attendance-tracking',
          '/solutions/parent-communication',
          '/solutions/school-broadsheet',
          '/use-cases',
          '/use-cases/fee-collection',
          '/use-cases/parent-communication',
          '/use-cases/results-publishing',
          '/use-cases/student-attendance',
          '/use-cases/school-broadsheet',
          '/use-cases/data-management',
          '/industries',
          '/industries/primary-schools',
          '/industries/secondary-schools',
          '/industries/international-schools',
          '/industries/early-childhood-centers',
          '/for-principals',
          '/for-bursars',
          '/for-teachers',
          '/for-parents',
          '/ghana-school-software',
          '/nigeria-school-software',
          '/kenya-school-software',
          '/uganda-school-software',
          '/south-africa-school-software',
          '/school-management-software',
          '/school-fee-management-software',
          '/attendance-management-software',
          '/results-publishing-software',
          '/parent-communication-software',
          '/school-broadsheet-software',
          '/security',
          '/success-stories',
          '/compare',
          '/compare/edumis',
          '/compare/manual-systems',
          '/compare/free-vs-paid',
          '/compare/google-forms',
          '/guides',
          '/guides/school-software-guide',
          '/video-tutorials',
          '/blog',
        ],
        disallow: [
          '/login',
          '/signup/verify',
          '/signup/success',
          '/forgot-password',
          '/reset-password',
          '/reset-pasword',
          '/purchase/success',
          '/admin',
          '/teacher',
          '/parent',
          '/accounting',
          '/schoolbase-admin',
          '/api',
          '/.next',
          '/node_modules',
        ],
      },
    ],
    sitemap: 'https://schoolbase.live/sitemap.xml',
    host: 'https://schoolbase.live',
  }
}
