import type { Metadata } from 'next'
import { Award, CheckCircle, DollarSign, Smartphone, TrendingUp, Zap } from 'lucide-react'
import { PublicAudienceShell } from '@/components/public-audience-shell'
export const metadata: Metadata = {
	title: 'SchoolBase for Uganda Schools | School Management Software Uganda',
	description: 'School management software for Uganda with fees, results, communication, and connected school operations workflows.',
	alternates: { canonical: 'https://schoolbase.live/uganda-school-software' },
	openGraph: { title: 'SchoolBase for Uganda Schools | School Management Software Uganda', description: 'School management software for Uganda with fees, results, communication, and connected school operations workflows.', url: 'https://schoolbase.live/uganda-school-software', type: 'website' },
}
export default function UgandaPage() { return <PublicAudienceShell eyebrow="SchoolBase for Uganda schools" title="A connected school management platform for Uganda." description="Bring administration, fees, mobile money workflows, results, communication, and parent updates into one clearer system." proofLabel="Uganda school operations" proofTitle="A practical system for daily work" sectionLabel="Built for Uganda schools" sectionTitle="Keep school records connected across the operations that matter." ctaTitle="Help your Uganda school work with more clarity and control." highlights={['Mobile money workflows', 'Fees and receipts', 'Results and reports', 'Attendance tracking', 'WhatsApp communication', 'Mobile-ready access']} features={[{ icon: Smartphone, title: 'Mobile money workflows', description: 'Keep payment updates and student account records easier for teams to follow.' }, { icon: DollarSign, title: 'Fee management', description: 'Track schedules, balances, payments, and receipts in one organized workflow.' }, { icon: TrendingUp, title: 'Results and reports', description: 'Give teachers and leaders a clearer view of academic performance.' }, { icon: Zap, title: 'Practical setup', description: 'Bring your school structure and daily records into one connected platform.' }, { icon: Award, title: 'Local support', description: 'Work with a platform designed to be understandable and useful for school teams.' }, { icon: CheckCircle, title: 'Parent updates', description: 'Keep families informed about the information that affects their students.' }]} /> }
