import type { Metadata } from 'next'
import { Award, CheckCircle, DollarSign, Smartphone, TrendingUp, Zap } from 'lucide-react'
import { PublicAudienceShell } from '@/components/public-audience-shell'
export const metadata: Metadata = {
	title: 'SchoolBase for Nigeria Schools | School Management Software Nigeria',
	description: 'School software for Nigeria with fee records, supported payment workflows, results, broadsheets, and configured communication.',
	alternates: { canonical: 'https://schoolbase.live/nigeria-school-software' },
	openGraph: { title: 'SchoolBase for Nigeria Schools | School Management Software Nigeria', description: 'School software for Nigeria with fee records, supported payment workflows, results, broadsheets, and configured communication.', url: 'https://schoolbase.live/nigeria-school-software', type: 'website' },
}
export default function NigeriaPage() { return <PublicAudienceShell eyebrow="SchoolBase for Nigeria schools" title="School management software for the way Nigerian schools operate." description="Connect administration, Paystack payments, results, broadsheets, communication, and parent updates in one practical school platform." proofLabel="Nigeria school operations" proofTitle="One clearer view from fees to results" sectionLabel="Built for Nigeria schools" sectionTitle="Bring the records behind school operations into one connected workflow." ctaTitle="Give your Nigerian school a stronger digital foundation." highlights={['Paystack payment workflows', 'WAEC and NECO structures', 'Fees and receipts', 'Results and broadsheets', 'WhatsApp communication', 'Parent access']} features={[{ icon: Smartphone, title: 'Payment workflows', description: 'Keep Paystack and other payment activity organized alongside student fee records.' }, { icon: DollarSign, title: 'Fee operations', description: 'Create schedules, track balances, issue receipts, and follow up consistently.' }, { icon: TrendingUp, title: 'Results visibility', description: 'Publish results and review academic patterns through a connected workflow.' }, { icon: Zap, title: 'School-ready setup', description: 'Set up your classes, staff, students, terms, and daily operations in one place.' }, { icon: Award, title: 'Built for local context', description: 'Use school management workflows that reflect how Nigerian teams work.' }, { icon: CheckCircle, title: 'Clear communication', description: 'Keep parents informed with timely updates around fees, attendance, and results.' }]} /> }
