import type { Metadata } from 'next'
import { Bell, Calculator, CheckCircle2, CreditCard, FileText, WalletCards } from 'lucide-react'
import { PublicProductShell } from '@/components/public-product-shell'
export const metadata: Metadata = {
	title: 'School Fee Management Software | SchoolBase',
	description: 'Manage itemized fee schedules, invoices, payments, receipts, reminders, and financial visibility in one platform.',
	alternates: { canonical: 'https://schoolbase.live/school-fee-management-software' },
	openGraph: { title: 'School Fee Management Software | SchoolBase', description: 'Manage itemized fee schedules, invoices, payments, receipts, reminders, and financial visibility in one platform.', url: 'https://schoolbase.live/school-fee-management-software', type: 'website' },
}
export default function SchoolFeeManagementSoftwarePage() { return <PublicProductShell eyebrow="School fee management" title="Make fee collection visible, organized, and easier to manage." description="Automate invoicing, payment tracking, receipts, and follow-up so school teams can focus on operations instead of chasing payments." proofTitle="Clearer billing, faster collections" sectionTitle="Give your finance team one reliable fee workflow." ctaTitle="Turn fee collection into a cleaner, faster system." highlights={['Fee schedules', 'Invoices and balances', 'Payment tracking', 'Digital receipts', 'Automatic reminders', 'Financial reports']} features={[{ icon: FileText, title: 'Fee schedules', description: 'Create clear charges and structured invoices for every class and student.' }, { icon: CreditCard, title: 'Payment tracking', description: 'Know what has been paid, what is overdue, and what needs attention.' }, { icon: WalletCards, title: 'Digital receipts', description: 'Issue consistent receipts and keep payment history ready when questions arise.' }, { icon: Bell, title: 'Automatic reminders', description: 'Follow up on outstanding fees with timely updates instead of manual chasing.' }, { icon: Calculator, title: 'Connected accounting', description: 'Keep fee collections aligned with the financial records your school relies on.' }, { icon: CheckCircle2, title: 'Clear reporting', description: 'Use collection summaries to understand cash flow and plan with confidence.' }]} /> }
