import type { Metadata } from 'next'
import { BarChart3, Bell, Calculator, CheckCircle2, FileText, WalletCards } from 'lucide-react'
import { PublicAudienceShell } from '@/components/public-audience-shell'

export const metadata: Metadata = {
	title: 'SchoolBase for Bursars | School Fee and Accounting Software',
	description: 'Manage school fees, receipts, invoices, and financial records with less manual reconciliation.',
	alternates: { canonical: 'https://schoolbase.live/for-bursars' },
	openGraph: { title: 'SchoolBase for Bursars | School Fee and Accounting Software', description: 'Manage school fees, receipts, invoices, and financial records with less manual reconciliation.', url: 'https://schoolbase.live/for-bursars', type: 'website' },
}

export default function BursarsPage() { return <PublicAudienceShell eyebrow="For bursars" title="Keep school finances accurate, visible, and easier to control." description="SchoolBase brings invoices, payments, receipts, reminders, and accounting records together so bursars can spend less time reconciling and more time managing cash flow." proofLabel="Finance workspace" proofTitle="Every payment has a clear place" sectionLabel="Your daily finance work" sectionTitle="Replace scattered records with one reliable financial workflow." ctaTitle="Give your finance team a cleaner way to collect and reconcile." highlights={['Invoices and fee schedules', 'Payment tracking', 'Digital receipts', 'Automatic reminders', 'Cashbook visibility', 'Financial reports']} features={[{ icon: FileText, title: 'Invoices and schedules', description: 'Create structured fee schedules and invoices that make every charge easy to understand.' }, { icon: WalletCards, title: 'Payment tracking', description: 'Know what has been paid, what is overdue, and which student account needs attention.' }, { icon: CheckCircle2, title: 'Digital receipts', description: 'Issue consistent receipts and keep payment history available when questions arise.' }, { icon: Bell, title: 'Automatic reminders', description: 'Follow up on outstanding fees with timely updates instead of manual chasing.' }, { icon: Calculator, title: 'Connected accounting', description: 'Keep fee collections and financial records aligned across the school.' }, { icon: BarChart3, title: 'Reports for decisions', description: 'Use clear summaries to understand collection performance and plan ahead.' }]} /> }
