import type { Metadata } from 'next'
import { Bell, CalendarDays, CheckCircle2, ShieldCheck, TrendingUp, Users } from 'lucide-react'
import { PublicProductShell } from '@/components/public-product-shell'
export const metadata: Metadata = {
	title: 'Student Attendance Management Software | SchoolBase',
	description: 'Track student attendance digitally, review summaries, and connect attendance to school communication workflows.',
	alternates: { canonical: 'https://schoolbase.live/attendance-management-software' },
	openGraph: { title: 'Student Attendance Management Software | SchoolBase', description: 'Track student attendance digitally, review summaries, and connect attendance to school communication workflows.', url: 'https://schoolbase.live/attendance-management-software', type: 'website' },
}
export default function AttendanceManagementSoftwarePage() { return <PublicProductShell eyebrow="Attendance management" title="Student attendance tracking that helps schools act earlier." description="Replace paper registers with fast attendance tracking, useful reports, and parent alerts that keep every class on track." proofTitle="Accurate attendance, less admin" sectionTitle="Make daily attendance a clear, connected school workflow." ctaTitle="Keep attendance accurate, visible, and easy to act on." highlights={['One-tap attendance', 'Parent absence alerts', 'Attendance reports', 'Absenteeism insight', 'Secure records', 'Teacher-friendly workflows']} features={[{ icon: CalendarDays, title: 'One-tap attendance', description: 'Mark attendance quickly on mobile or desktop and keep daily records accurate.' }, { icon: Bell, title: 'Parent alerts', description: 'Send timely updates when a student is absent or an attendance issue needs attention.' }, { icon: TrendingUp, title: 'Attendance reports', description: 'View trends by class and student so leaders can respond to patterns sooner.' }, { icon: CheckCircle2, title: 'Reduce absenteeism', description: 'Use connected data to follow up consistently and support better attendance.' }, { icon: ShieldCheck, title: 'Secure records', description: 'Keep attendance information available only to the staff who should see it.' }, { icon: Users, title: 'Teacher-friendly', description: 'Give teachers a workflow that is quick enough for the busiest school day.' }]} /> }
